### ISSUE TITLE
Attempt to see other player

### ISSUE THREAD

**Issue by valkyrienyanko** [Valks-Games/sankari#105]
I started both clients up. Started the level. And the other client instantly crashed. While on the host I could see the "other" player moving to match the hosts movements. So it seems it wasn't the other player but the host seeing its own movements. Anyways that's only half the issue as I have no idea why the other client crashed.

![image](https://user-images.githubusercontent.com/6277739/189547097-445b992f-9460-4bd2-b470-591ecf08c011.png)

**Comment by policiu** [comment]
Did you consider using https://docs.godotengine.org/en/stable/tutorials/networking/high_level_multiplayer.html instead of rolling our own?

Regardless, here is the initial results:
![movement!](https://user-images.githubusercontent.com/1704165/189801654-8339c2f9-22c3-49af-ad79-b0d0b2982eaf.gif)
