### ISSUE TITLE
"[Warning] Level scene is null" when playing multiplayer

### ISSUE THREAD

**Issue by valkyrienyanko** [Valks-Games/sankari#116]
### Steps to Reproduce
1. Play with host client and other client in a level

## Host Client Log

![image](https://user-images.githubusercontent.com/6277739/190044402-fcf4df2f-c138-47cf-9567-16e90389c26d.png)

## Other Client Log

![image](https://user-images.githubusercontent.com/6277739/190044507-e2323322-9ff9-42e5-8642-326d5776fa59.png)

**Comment by policiu** [comment]
Picking up

**Comment by valkyrienyanko** [comment]
Transferring issue to #168
