### ISSUE TITLE
[Godot 4] How do you set the game window title?

### ISSUE THREAD

**Issue by valkyrienyanko** [Valks-Games/sankari#131]
> ℹ️ This issue is for the `godot4` branch

In Godot 3.x it was `OS.SetWindowTitle(string title);` but in Godot 4 this is no longer the case.

[Link to Godot Discord to ask this question](https://discord.gg/VwphYtF9rw)

**Comment by policiu** [comment]
Os was split into OS and DisplayServer: https://github.com/godotengine/godot/pull/37317

`DisplayServer.WindowSetTitle("I'm a title!");`
