### ISSUE TITLE
All non-multiplayer related issues for the Player

### ISSUE THREAD

**Issue by valkyrienyanko** [Valks-Games/sankari#136]
> ℹ️ The player script extends from `CharacterBody2D` ([click to see docs for CharacterBody2D](https://docs.godotengine.org/en/latest/classes/class_characterbody2d.html?highlight=CharacterBody2D))

## Movement

![wall1](https://user-images.githubusercontent.com/6277739/194910007-f66e2a36-d54d-49a6-a1c2-83e6dd14b843.gif)
- [ ] Wall jump physics needs to be revised, feels dull as it is right now. (This can be fixed by making it so commands can be run for a certain duration. Instead of the wall jump velocity being applied one frame it could be applied for a couple of frames then the command could be stopped. This can be achieved with a GTimer.)

**Comment by valkyrienyanko** [comment]
Regarding the "Touching Bottom Area" issue I have commented out 2 sections of code where I thought the issue was occurring but after commenting out these sections I get the exact same error printed to console as before.

![image](https://user-images.githubusercontent.com/6277739/193165992-4b889d15-c7d5-4976-aaee-ff9e01947fcb.png)

![image](https://user-images.githubusercontent.com/6277739/193166013-f1cc0713-808b-4b7a-ab36-cbed186e2563.png)

**Comment by valkyrienyanko** [comment]
Player death animation has been fixed 100%!

**Comment by valkyrienyanko** [comment]
For the "Player falls insanely fast when walking off a ledge" the y velocity is constantly being logged as `900` !!! when the player is on the ground. This is not good! This should be a value of `0` when the player is touching the ground. However when I constantly set this to `0` while the player is on the ground I can no longer jump.

![image](https://user-images.githubusercontent.com/6277739/193207239-14c26f51-2043-463b-b453-5ce1fe697980.png)

**Comment by policiu** [comment]
Planning on cleaning up Player.cs

**Comment by valkyrienyanko** [comment]
I'm working on player script rn, I'll let you know when I'm done

**Comment by valkyrienyanko** [comment]
Done working on Player

**Comment by policiu** [comment]
>  Death screen showing "lives x 3" is not visible on death (just see black screen)

I think the issue is that we don't initialize the UI on InstantLoadLevel (or whatever)

**Comment by valkyrienyanko** [comment]
I disabled `InstantLoadLevel` when loading the test level but I still see black, this didn't fix it for me.

**Comment by policiu** [comment]
I misspoke, you need to also disable level loading and go through the normal level select process.

**Comment by valkyrienyanko** [comment]
Solved lives not appearing issue 880b09e18e7878a2590d9fec1933d23982068422

**Comment by jackadgery** [comment]
Haven't looked in code yet, and am unsure how to use git, but, make a wallJumped bool, and set to true on wall jump, then false on contact with ground? Should stop infinite wall jumps

**Comment by policiu** [comment]
> Haven't looked in code yet, but make a wallJumped bool, and set to true on wall jump, then false on contact with ground? Should stop infinite wall jumps

I think this issue is more nuanced. For example, are we trying to prevent infinite wall jumping on a single wall, but bouncing between walls is fine? How should dashing interact with wall jumping? Etc.

>  am unsure how to use git
I hear GitHub's desktop app is pretty good. 
Alternatively you could read the docs, here is a generic guide to git that doesn't assume GitHub:
https://git-scm.com/docs/gittutorial

**Comment by valkyrienyanko** [comment]
The first thing I can think of is
```
if wall direction is the same as previous wall direction and wall jump count > 1
    prevent wall jump until touch ground
else if wall direction different then previous wall direction
    do nothing as we are bouncing between walls
```

But it could really take any approach. For example wall jumping could become harder after `x` jumps. Or maybe it's a hard reset after wall jumping `x` times on different or same wall.

But for now I think the pseudo code I mentioned above is what should be done for now.
