### ISSUE TITLE
Should I Use A State Machine For The Player Code?

### ISSUE THREAD

**Issue by valkyrienyanko** [Valks-Games/sankari#21]
I have seen people use state machines in tutorials for player movement but this often involves a lot of duplicate code but I guess the main player state manager script would have a bunch of methods to reduce the duplicate code. I have tried this before but it made the player logic much more complicated and many issues arose. For example the player was not jumping because they were not in a state that would allow jumping. (The switching of states was too slow, a frame behind causing big annoyance)

**Comment by Smokedelephant** [comment]
I don’t think we’ll need it due to the idea that valk and i talked about. It could all be handled in the script.
