### ISSUE TITLE
Dependency Injection or Static? And what about singletons?

### ISSUE THREAD

**Issue by valkyrienyanko** [Valks-Games/sankari#22]
Should I have a game manager super class that has references to all the other manager scripts like audio manager and level manager and pass this reference of game manager to everything and access everything through game manager script OR should I make game manager and/or some of the other managers static as well and just watch out for cleanup after using static. Also what's the deal with singletons, what's the point of them? I feel like singletons make readability worse. Why not make everything static in the class so it's easier to type?

**Comment by Smokedelephant** [comment]
I dont know much about this but from my research static may be faster and give more stable frame rates

**Comment by valkyrienyanko** [comment]
I don't care about performance when it comes to DI / Static / Singletons. I'm asking in terms of readability. I think using static would make things more readable in the short run but DI was developed to improve readability in the long run.

**Comment by valkyrienyanko** [comment]
I have come to the conclusion to use whatever I am most comfortable with and that is a using a mix of both.
