### ISSUE TITLE
What Should Coins Do?

### ISSUE THREAD

**Issue by valkyrienyanko** [Valks-Games/sankari#25]
I want to add some kind of collectible (coins or gems or something shiny you know) to each level but I'm not sure what they should do. Should they increase the game score? Affect player lives? Act as a currency for a shop? Or do nothing and just increase a number on your screen that you can brag about to your friends.

**Comment by Smokedelephant** [comment]
Maybe a shop that appears at the end of levels that you can buy gear/heals from or a system like mario where coins are your lives and if you die and have 0 coins you restart the area
