### ISSUE TITLE
Level placement of coins is tedious. Helpers should be made to help with this.

### ISSUE THREAD

**Issue by valkyrienyanko** [Valks-Games/sankari#49]
Placing coins requires the level designer to copy paste coins which in Godot can prove to become tedious. There should be scripts to help automate this.

There should be a script that places coins in a circle (whether it be just the outline or the full circle) and a script for placing coins in a row. Disabled Area2D's should be used to get the radius / width of where the coins should go. To get an idea of how Area2D's are to be used, have a look at the prefab in `res://Scenes/Prefabs/Platforms/Platform Circle.tscn`

For the circle coin helper the properties should look something as follows
```cs
[Export] public bool onlyOutline; // if disabled, circle and outline are filled with coins distributed evenly
// no need for radius property as it's handled by the Area2D
```

For the row coin helper the properties should look something as follows
```cs
// no properties as Area2D tells script everything it needs to know (where the coins need to go)
```

**Comment by Soroosh-Sharif** [comment]
Hello, I would like to work on this feature but don't have much time. If its not high on your to-do list, I can help with it.

**Comment by valkyrienyanko** [comment]
Closing this issue as the description of this issue is sparse and takes away attention from what needs to be tackled right now. A new issue regarding this will be open at a later date.
