### ISSUE TITLE
coins should be reset on death

### ISSUE THREAD

**Issue by valkyrienyanko** [Valks-Games/sankari#60]

**Comment by AdamLaine** [comment]
Should coin number be reset on every death (including the checkpoint)? Or only the death where we start the level from the beginning?

**Comment by valkyrienyanko** [comment]
## Scenario 1
Lets say you start on level 1, you get 3 coins but then you die. Those 3 coins should be reset to 0. (or however many coins you had before you started the level)

## Scenario 2
You have 23 coins, you reach a checkpoint, now you keep these 23 coins. You gain 3 more coins but then you die. You should lose these 3 coins and your coins should be reset to 23.
