### ISSUE TITLE
Checkpoint flag animations are not set to "captured" if a level is restarted because a player died

### ISSUE THREAD

**Issue by valkyrienyanko** [Valks-Games/sankari#66]

**Comment by JefvdA** [comment]
Is this issue still needed? When testing, after respawning the checkpoint is still having the "captured" animation, and it is still active aswell as I respawn besides the checkpoint.

**Comment by valkyrienyanko** [comment]
This is because the player spawns right on top of the checkpoint instantly activating the "captured" animation. If there were 2 checkpoints (1 earlier in the level, that checkpoint would not activated)

This is not a big deal as you'll never go all the way back to see this in the level.

However I want to play a sound when the flag is captured and I want the sound to play only when you capture it. If I were to add a sound now, it would play not only when you captured the flag, but whenever you died and respawned at the flag.

This is why I want to enable it before the player respawns in the level. (when the player dies they reload the entire level, the level is QueueFree() and readded with AddChild() wiping everything)

**Comment by JefvdA** [comment]
Hey I'd like to work on this issue if that's ok.

Just one question:

> If there were 2 checkpoints (1 earlier in the level, that checkpoint would not activated)
> This is not a big deal as you'll never go all the way back to see this in the level.

So should I just ignore the fact that a level could have 2 checkpoints? And only activate the checkpoint where the player will respawn? Thanks :)

**Comment by valkyrienyanko** [comment]
> So should I just ignore the fact that a level could have 2 checkpoints? And only activate the checkpoint where the player will respawn? Thanks :)

A player may decide to go to the beginning of the level again to find a collectible that they missed. So eventually it would be nice if all checkpoints were checked but just checking the checkpoint the player is currently respawned at is fine for now.

**Comment by JefvdA** [comment]
Hey quick question, how do you debug godot? Cause I setup vscode to work with godot (everything works except opening godot from vscode itself, but intelisense etc is working). I just can't quite get my head around debugging through vscode.

**Comment by valkyrienyanko** [comment]
Under `Godot > Project > Project Settings > Mono > Debugger Agent` take note of the port and make sure `Wait For Debugger` is checked.

In VSCode make sure you have these extensions

![image](https://user-images.githubusercontent.com/6277739/188503478-3af90d44-3e50-4591-8cdb-45ff799503d8.png)

Under `.vscode/` I have these 3 files setup for the Godot Modules CSharp project (have not debugged this current project yet but it should be very similar for setup)

`launch.json`

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "MoonSharp Attach",
            "type": "moonsharp-debug",
            "request": "attach",
            "debugServer": 41912
        },
        {
            "name": "Play in Editor",
            "type": "godot-mono",
            "mode": "playInEditor",
            "request": "launch"
        },
        {
            "name": "Launch",
            "type": "godot-mono",
            "request": "launch",
            "mode": "executable",
            "preLaunchTask": "build",
            "executable": "C:/Users/VALK-DESKTOP/Downloads/Godot_v3.4.4-stable_mono_win64/Godot_v3.4.4-stable_mono_win64.exe\r",
            "executableArguments": [
                "--path",
                "${workspaceRoot}"
            ]
        },
        {
            "name": "Launch (Select Scene)",
            "type": "godot-mono",
            "request": "launch",
            "mode": "executable",
            "preLaunchTask": "build",
            "executable": "C:/Users/VALK-DESKTOP/Downloads/Godot_v3.4.4-stable_mono_win64/Godot_v3.4.4-stable_mono_win64.exe\r",
            "executableArguments": [
                "--path",
                "${workspaceRoot}",
                "${command:SelectLaunchScene}"
            ]
        },
        {
            "name": "Attach",
            "type": "godot-mono",
            "request": "attach",
            "address": "localhost",
            "port": 23685
        }
    ]
}
```

`settings.json`

```json
{
    "godot_tools.editor_path": "c:\\Users\\VALK-DESKTOP\\Downloads\\Godot_v3.5-stable_mono_win64\\Godot_v3.5-stable_mono_win64.exe"
}
```

`tasks.json`

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "C:/Users/VALK-DESKTOP/Downloads/Godot_v3.4.4-stable_mono_win64/Godot_v3.4.4-stable_mono_win64.exe\r",
            "type": "process",
            "args": [
                "--build-solutions",
                "--path",
                "${workspaceRoot}",
                "--no-window",
                "-q"
            ],
            "problemMatcher": "$msCompile"
        }
    ]
}
```

I know there are buttons in vscode to auto generate some of these files. Just can't remember how right now.

This should allow you to open Godot through VSCode by hitting F1 in vscode and typing `Godot Tools: Open workspace with godot editor`. Although that does not answer your question about debugging.

You should be able to click on the debugger tab in VSCode and there should be a option to attach to Godot. Once vscode debugger is attached and running and you set a breakpoint. Run Godot and debugging should work.

Note that vscode debugging is very annoying as you have to "watch" every variable you want to track. You can't just hover your mouse over that variable and see its value.

**Comment by JefvdA** [comment]
Hey, I think the problem is with my ubuntu installation.

I was fiddling around to get it to work but now I managed to get my .net installation broken :/

Is it ok if I leave this issue be for someone else? I might come back to this project when I figure things out with my installation.

Sorry, and good luck with the project :)

**Comment by valkyrienyanko** [comment]
Closing this issue as the description of this issue is sparse and takes away attention from what needs to be tackled right now. A new issue regarding this will be open at a later date.
