### ISSUE TITLE
[Netcode] bob is not seeing valk

### ISSUE THREAD

**Issue by valkyrienyanko** [Valks-Games/sankari#84]
> ⚠️ This issue is on the "netcode" branch!

Players are listed top right.

![image](https://user-images.githubusercontent.com/6277739/189024909-f9f73f32-2eba-4e87-a28e-a97210c28191.png)

## Steps to Reproduce
1. Host as valk
2. Join as bob

## Code
1. Switch to `netcode` branch
2. Have a look at this code  

https://github.com/Valks-Games/sankari/blob/a234383561fddb68ef5ed9b6470c2a20af9c9cac/Scripts/Netcode/Packets/CPacketPlayerJoinServer.cs#L36-L53

**Comment by valkyrienyanko** [comment]
![image](https://user-images.githubusercontent.com/6277739/189195631-cbfd689b-6504-4818-9bfd-a7cf2d316c5d.png)

**Comment by simon-curtis** [comment]
Can you put some timestamps on the console output?

**Comment by valkyrienyanko** [comment]
The problem is because the Send() method does not have any peers specified. So the packet.Peers has a length of 0 and thus the packet is sent to no one!

**Comment by simon-curtis** [comment]
Okay, I'm just getting the GODOT environment setup as I have not before - or do you feel you can fix it from here?

**Comment by valkyrienyanko** [comment]
I have a good feeling I can fix it from here thanks!

**Comment by valkyrienyanko** [comment]
`CPacketPlayerJoinServer.cs`
![image](https://user-images.githubusercontent.com/6277739/189201450-cc4924fa-78e0-45b0-92ca-7e9edbeb8519.png)

This is all that I had to do to fix this issue.

**Comment by valkyrienyanko** [comment]
I should probably warn the coder somehow if zero peers are specified for these Send() methods.

**Comment by valkyrienyanko** [comment]
The coder is now forced to specify at least one peer so no one will run into this issue ever again. 059b076c60438213286e330d56d449f3f8ce06d3
