### ISSUE TITLE
Starting 2 game exes at same time from batch file

### ISSUE THREAD

**Issue by valkyrienyanko** [Valks-Games/sankari#87]
```batch
start "Super Mario Bros Like Game.exe"
start "Super Mario Bros Like Game.exe"
```

This opens up 2 blank terminals and does not launch the game in either instances.

How can I launch the game twice via a script like this?

The reason I want this is because it is tedious to double click the games exe twice to open up 2 instances when debugging multiplayer code.

**Comment by policiu** [comment]
Here is a[ VSCode config to launch](https://gist.github.com/policiu/a058cd8791ce79e481023b90790f247c) (maybe we should create a template in the repo).
![multipleSessions](https://user-images.githubusercontent.com/1704165/189553091-6e30a301-1aed-471f-922f-cea57e300e70.gif)

**Comment by valkyrienyanko** [comment]
I get this when I try to launch `Launch 2 sessions` configuration

![image](https://user-images.githubusercontent.com/6277739/189555161-e9dddcd6-d19d-4ee0-a81e-abe6aa2470a7.png)

**Comment by policiu** [comment]
Updated the gist with the build json.

It's not great, but it shows up in the debugging terminal:

![multipleSessionsTerminal](https://user-images.githubusercontent.com/1704165/189557387-6cac03dd-64ec-483c-840f-d9587dcfacd5.gif)

**Comment by valkyrienyanko** [comment]
Is it possible to set the positions of the windows when they are created through `launch.json` so one window is on the left and the other on the right?

**Comment by policiu** [comment]
There is probably some weird way to get it to work, but I couldn't figure it out which is why it isn't great. Breakpoints and exception capturing works though.

The name is from the launch.json. Just change those names and make sure combination references them.

You could probably launch consoles if you don't want debugging.

**Comment by valkyrienyanko** [comment]
Thank you for this. I will close this issue when I update the contributing guide for coders with the tasks.json and launch.json files you provided.

**Comment by valkyrienyanko** [comment]
Closing because of 6a37bbd22d43b02fa3537272e31ce87199f4f55a
