### ISSUE TITLE
Consider making builds with debugging symbols

### ISSUE THREAD

**Issue by valkyrienyanko** [Valks-Games/sankari#97]
Debug symbols are not shown in exceptions on exported builds.

An example of an exception from server thread
```
Unhandled Exception:
System.Collections.Generic.KeyNotFoundException: The given key '0' was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in <c84d94161bca414384015e66544862cf>:0
  at Sankari.SPacketPlayerPositions.Handle () [0x00063] in <b8d2b5c6ae754e649826eb15d3415fe1>:0
  at Sankari.GodotCommands.Update () [0x00142] in <b8d2b5c6ae754e649826eb15d3415fe1>:0
  at Sankari.Netcode.Net.Update () [0x0006e] in <b8d2b5c6ae754e649826eb15d3415fe1>:0
  at Sankari.GameManager.Update () [0x00068] in <b8d2b5c6ae754e649826eb15d3415fe1>:0
  at Sankari.Linker._Process (System.Single delta) [0x00074] in <b8d2b5c6ae754e649826eb15d3415fe1>:0
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <c84d94161bca414384015e66544862cf>:0
  at Godot.GodotSynchronizationContext.ExecutePendingContinuations () [0x00021] in <8c99985ff12947baa88b379583357ac3>:0
  at Godot.GodotTaskScheduler.Activate () [0x0000e] in <8c99985ff12947baa88b379583357ac3>:0
  at (wrapper native-to-managed) Godot.GodotTaskScheduler.Activate(Godot.GodotTaskScheduler,System.Exception&)
```

**Comment by policiu** [comment]
Picking up issue.

**Comment by policiu** [comment]
Looked at this for a bit, but I'm confused. This looks like an error printed during a release build (or at least missing debug symbols). (We can see this by the <file name>:line (e.g. <c84d94161bca414384015e66544862cf>:0). So, even if we show the line number, it probably won't be helpful as the compiler can move them around.

Do you have a min example? I haven't been able to find this exact formatted error. (Our logger adds "[Error]" and Godot just closes on unhandled exceptions and if I handle them, they look much different).

If this is just talking about Logger.cs, then we can add the info pretty easily.

**Comment by valkyrienyanko** [comment]
https://github.com/Valks-Games/sankari/blob/5c0604f0b2b090680fc77aec5b3f4cb9ce25f928/Scripts/Netcode/Server/GameServer.cs#L13-L14

Add `throw new Exception("foo");` in this constructor.

**Comment by valkyrienyanko** [comment]
Ah I remember now. The error was here 

https://github.com/Valks-Games/sankari/blob/5c0604f0b2b090680fc77aec5b3f4cb9ce25f928/Scripts/Netcode/Packets/SPacketPlayerPositions.cs#L31-L47

I was getting "key not found" in dictionary error. I know why I was getting the error and I fixed it. But it was time consuming because I didn't see the line numbers in the error in exported release.

**Comment by valkyrienyanko** [comment]
I suppose fixing this would be done by surrounding this line of code with a try catch and making use of `Logger.LogErr(e, "Client")`

**Comment by valkyrienyanko** [comment]
Just did that and it's not showing the line numbers?

![image](https://user-images.githubusercontent.com/6277739/189504487-44344cb7-92af-4002-956a-a620766cf5b2.png)

**Comment by valkyrienyanko** [comment]
Here is what `Logger.LogErr()` is doing behind the scenes btw.

https://github.com/Valks-Games/sankari/blob/5c0604f0b2b090680fc77aec5b3f4cb9ce25f928/Scripts/Static/Logger.cs#L16-L22

https://github.com/Valks-Games/sankari/blob/5c0604f0b2b090680fc77aec5b3f4cb9ce25f928/Scripts/Static/Logger.cs#L63-L67

https://github.com/Valks-Games/sankari/blob/5c0604f0b2b090680fc77aec5b3f4cb9ce25f928/Scripts/Static/Logger.cs#L88-L92

**Comment by valkyrienyanko** [comment]
I just tried replacing `GD.PrintErr(v)` with `Console.WriteLine(v)` and they print the same thing. I thought that might be the culprit but I guess not.

**Comment by valkyrienyanko** [comment]
Btw to reproduce this error do the following

1. Surround this line with try catch and put `Logger.Log(exception, "Client")` in the catch
https://github.com/Valks-Games/sankari/blob/5c0604f0b2b090680fc77aec5b3f4cb9ce25f928/Scripts/Netcode/GodotCommands.cs#L28
2. Build an exported release
3. Make sure `enet.dll` is next to the games exe
4. Launch 2 instances of the game in their respective cmd windows (launch the game exe through cmd windows)
5. Press "Play" in each game
6. In one of the games press Esc once in the map screen to open up the multiplayer menu
7. Click "Host"
8. In the other game do the same to bring up the menu, click on "Join" tab, and change the player name to something other than valk and then click "Join other world"

**Comment by valkyrienyanko** [comment]
Maybe because the `Handle()` method return type is a `Task` is part of the reason there are no line numbers? Maybe the try catch needs to go directly beside where the exception is thrown? If so that would be very tedious and ugly to see try catches everywhere in each `Handle()` method.

**Comment by policiu** [comment]
Without Debugging symbols, the call stack will not have line numbers. 

We could do something like LogDebug does to get the line number of the throw location, but that doesn't help too much, it would look like this:
```C#
    private void _on_Play_pressed()
    {
        try
        {
            List<string> apple = new List<string>();
            apple[0].Trim();
        }
        catch (Exception ex)
        {
            Logger.LogErr(ex);
        }
    }
```


```
[Error] Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index\n  at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) [0x00009] in <c84d94161bca414384015e66544862cf>:0
  at Sankari.UIMenu._on_Play_pressed () [0x00005] in <ec5557f7f5344d39a1123e776feb6caa>:0
  at Scripts\UI\UIMenu.cs:_on_Play_pressed:14 
```

**Comment by valkyrienyanko** [comment]
I used the LogDebug. I think you mean like this? This isn't helpful at all though.

![image](https://user-images.githubusercontent.com/6277739/189505201-80f3fa9f-fe37-47ba-88ff-ba8f6ef30b8a.png)

I also found a bug. `GameManager.Console.AddMessage(result.Data);` should be `GameManager.Console.AddMessage(data.Message);`

**Comment by valkyrienyanko** [comment]
Fixed bug mentioned above c26d984c04564e0fb54316b451013af3b83be52a

**Comment by valkyrienyanko** [comment]
Even when the try catch is directly next to the exception throw I see no line numbers...

![image](https://user-images.githubusercontent.com/6277739/189505312-a49663f8-1a42-4738-8c4b-b86364a439f4.png)

**Comment by valkyrienyanko** [comment]
![image](https://user-images.githubusercontent.com/6277739/189505323-3528b6cf-9878-4c15-b246-c0689df603d5.png)

**Comment by valkyrienyanko** [comment]
> Without Debugging symbols, the call stack will not have line numbers.

What do you mean by debugging symbols? What are they? And when do you know when they will be present?

**Comment by policiu** [comment]
Debugging symbols only appear when building in Debug mode. 

In my fork I have line numbers present for log error:
https://github.com/Valks-Games/sankari/compare/main...policiu:sankari:logger-lines#diff-f2549b57dc0702feaa14ecebf7bb0b5808da6edbbd939447808ab79b980d9c93R1

**Comment by valkyrienyanko** [comment]
In Godot, I always have "Export with Debug" checked on when I export the game. Is that what you mean by debug mode?

![image](https://user-images.githubusercontent.com/6277739/189505679-0318f749-fc2c-4a30-96b8-1a109b068020.png)

![image](https://user-images.githubusercontent.com/6277739/189505668-987e8816-c9e2-4374-80be-7c2b0dd91ea8.png)

**Comment by policiu** [comment]
Godot export builds uses release_debug which strips debug symbols (also is faster than a debug build). I assume that the reason why we don't have our symbols.

For deving, I use the launch task in Visual Studio Code which launches the editor which has our debug symbols. When you create the tasks and launch.json from the debug tab, use the C# Godot option. 

Here is mine if you need it: https://gist.github.com/policiu/4d88974f07c2168a06f9bc37a59f4665

Anyway, once you start it, here is the debug console output:

```
Unhandled Exception:
System.Exception: A crash!

  at Sankari.SPacketGameInfo.Handle () [0x0000f] in C:\Games\Dev\sankari\Scripts\Netcode\Packets\SPacketGameInfo.cs:106 

  at Sankari.GodotCommands.Update () [0x000f3] in C:\Games\Dev\sankari\Scripts\Netcode\GodotCommands.cs:28 

  at Sankari.Netcode.Net.Update () [0x00025] in C:\Games\Dev\sankari\Scripts\Netcode\Net.cs:66 

  at Sankari.GameManager.Update () [0x0001f] in C:\Games\Dev\sankari\Scripts\Managers\GameManager.cs:62 

  at Sankari.Linker._Process (System.Single delta) [0x0002b] in C:\Games\Dev\sankari\Scripts\Linker.cs:26 

  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <c84d94161bca414384015e66544862cf>:0 

  at Godot.GodotSynchronizationContext.ExecutePendingContinuations () [0x00013] in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/GodotSynchronizationContext.cs:21 

  at Godot.GodotTaskScheduler.Activate () [0x00008] in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/GodotTaskScheduler.cs:59 

  at (wrapper native-to-managed) Godot.GodotTaskScheduler.Activate(Godot.GodotTaskScheduler,System.Exception&)
```



---------

Looking ahead, probably need to decide how testers and other groups get debug builds. 
I'm not sure how to get the debug symbols, but based on [this reddit thread](https://www.reddit.com/r/godot/comments/pqhvkg/help_with_exporting_pck_files/), we would need to build godot in debug mode, then setup an export template to use the it.  

For now though, I don't think it's worth pursing. I'll make a pull request with the changes to the logger I made.

Request to make a new issue and close this or update the title.
-> Consider making builds with debugging symbols.

**Comment by valkyrienyanko** [comment]
I realize this issue isn't that big of a deal.

If I run into an error with no debug symbols, I can reproduce that issue by running the game from within the Godot engine with debug symbols.

I'm going to close this issue. Feel free to make a new one if you want.
